### ISSUE TITLE
https://pyscript.net/releases/latest/pyscript.js 404

### ISSUE THREAD

**Issue by henrissl** [pyscript/pyscript.net#78]
Why is https://pyscript.net/releases/latest/pyscript.js and https://pyscript.net/releases/latest/pyscript.css broken, and how can I help get it working again?

**Comment by WebReflection** [comment]
Because it was never meant to be stable or used in production and because PyScript changed over the last 2 years in a huge way and people still using those endpoints always had issues with our recent effort to provide a better API, a better documentation, and whatnot.

Those end points are not likely coming back, so far they caused only pain to both users and ourselves, but if you really believe that's the unstable channel you'd like to use, we wrote how to be on such channel with the latest offer we have: https://docs.pyscript.net/2024.11.1/faq/#pyscript-latest
